#created by Apache Tomcat Maven plugin
#Tue Apr 28 15:45:59 CEST 2026
accessLogValveFormat=%h %l %u %t %r %s %b %I %D
connectorhttpProtocol=HTTP/1.1
enableNaming=false
generationTimestamp=1777383959304
useServerXml=false
wars=inscription-course.war|/inscription-course
